#!/usr/bin/env bash
# One-time setup: Helix + local chat (llama-server) + images (ComfyUI + FLUX).
#
# Layout (sibling folders next to this repo):
#   ../llama-bin/llama-server
#   ../llama.cpp/models/*.gguf
#   ../ComfyUI/
#
# Usage:
#   ./scripts/install-local.sh           # full install (~15–20 GB models)
#   ./scripts/install-local.sh --quick   # chat only, skip image models
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKSPACE="$(cd "$ROOT/.." && pwd)"
# shellcheck source=scripts/lib/download.sh
source "$ROOT/scripts/lib/download.sh"

QUICK=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --quick) QUICK=1 ;;
    -h|--help)
      echo "Usage: $0 [--quick]"
      echo "  --quick   Install app + chat model only (skip ComfyUI / FLUX)"
      exit 0
      ;;
  esac
  shift
done

LLAMA_BIN_DIR="$WORKSPACE/llama-bin"
LLAMA_MODELS="$WORKSPACE/llama.cpp/models"
COMFY_DIR="$WORKSPACE/ComfyUI"
CHAT_MODEL="Qwen2.5-7B-Instruct-Q4_K_M.gguf"
CHAT_MODEL_URL="https://huggingface.co/bartowski/Qwen2.5-7B-Instruct-GGUF/resolve/main/${CHAT_MODEL}"
FLUX_CKPT="flux1-schnell.safetensors"
# Comfy-Org merged checkpoint for CheckpointLoaderSimple workflows
FLUX_CKPT_URL="https://huggingface.co/Comfy-Org/flux1-schnell/resolve/main/${FLUX_CKPT}"

echo "=== Helix local install ==="
echo "Workspace: $WORKSPACE"
echo "Repo:      $ROOT"
echo ""

# --- Toolchain ---
for cmd in node npm git curl; do
  if ! command -v "$cmd" >/dev/null; then
    echo "[helix] missing required command: $cmd"
    exit 1
  fi
done
echo "[helix] node $(node -v) · npm $(npm -v)"

# --- Helix app ---
cd "$ROOT"
if [[ ! -d node_modules ]]; then
  echo "[helix] npm install…"
  npm install
else
  echo "[helix] node_modules present"
fi

# --- .env.local for local-only ---
ENV_LOCAL="$ROOT/.env.local"
if [[ ! -f "$ENV_LOCAL" ]]; then
  cat >"$ENV_LOCAL" <<'EOF'
# Helix local bundle — generated by scripts/install-local.sh
AI_LOCAL_ONLY=true
AI_PROVIDER=local
AI_PREFER_LOCAL=true

# Optional cloud (comment out AI_LOCAL_ONLY above to use HF on Vercel / when credits return)
# HF_API_KEY=
# HF_MODEL=Qwen/Qwen2.5-7B-Instruct
EOF
  echo "[helix] wrote $ENV_LOCAL (local-only mode)"
else
  echo "[helix] .env.local exists (not overwritten)"
fi

# --- llama-server binary ---
ARCHIVE="$(llama_archive_name)" || {
  echo "[helix] unsupported OS/arch for bundled llama-server: $(uname -s) $(uname -m)"
  echo "[helix] install llama-server manually and set LLAMA_BIN"
  exit 1
}
TAG="$(llama_release_tag)"
LLAMA_URL="https://github.com/ggml-org/llama.cpp/releases/download/${TAG}/${ARCHIVE}"

if [[ ! -x "$LLAMA_BIN_DIR/llama-server" ]]; then
  TMP="$WORKSPACE/.helix-install-llama.tgz"
  download_file "$LLAMA_URL" "$TMP"
  mkdir -p "$LLAMA_BIN_DIR"
  tar -xzf "$TMP" -C "$LLAMA_BIN_DIR" --strip-components=1
  rm -f "$TMP"
  chmod +x "$LLAMA_BIN_DIR/llama-server" 2>/dev/null || true
  xattr -dr com.apple.quarantine "$LLAMA_BIN_DIR" 2>/dev/null || true
  echo "[helix] llama-server → $LLAMA_BIN_DIR/llama-server"
else
  echo "[helix] llama-server present"
fi

# --- Chat model (GGUF) ---
download_file "$CHAT_MODEL_URL" "$LLAMA_MODELS/$CHAT_MODEL"

if [[ "$QUICK" -eq 1 ]]; then
  echo ""
  echo "[helix] --quick: skipping ComfyUI / FLUX"
  echo "[helix] Done. Run: npm run start:local"
  exit 0
fi

# --- ComfyUI ---
PY="$(find_python312)" || {
  echo "[helix] Python 3.11+ required for ComfyUI (install python3.12)"
  exit 1
}
echo "[helix] using $PY ($("$PY" --version))"

if [[ ! -f "$COMFY_DIR/main.py" ]]; then
  echo "[helix] cloning ComfyUI…"
  git clone --depth 1 https://github.com/Comfy-Org/ComfyUI.git "$COMFY_DIR"
fi

if [[ ! -d "$COMFY_DIR/.venv" ]]; then
  echo "[helix] ComfyUI venv + deps (may take several minutes)…"
  "$PY" -m venv "$COMFY_DIR/.venv"
  "$COMFY_DIR/.venv/bin/pip" install -U pip
  "$COMFY_DIR/.venv/bin/pip" install torch torchvision torchaudio
  "$COMFY_DIR/.venv/bin/pip" install -r "$COMFY_DIR/requirements.txt"
fi

# --- FLUX checkpoint for Helix workflows ---
download_file "$FLUX_CKPT_URL" "$COMFY_DIR/models/checkpoints/$FLUX_CKPT"

mkdir -p "$HOME/.helix/logs"

echo ""
echo "=== Install complete ==="
echo "  Chat:   http://127.0.0.1:8080  (llama-server / qwen-7b)"
echo "  Images: http://127.0.0.1:8188  (ComfyUI)"
echo "  Helix:  http://localhost:3000"
echo ""
echo "Start everything:  cd $ROOT && npm run start:local"
echo "Stop:              npm run stop:local"
